[package]
name = "impact_profiling"
description = "Performance profiling utilities for the Impact engine"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
criterion = ["dep:criterion"]
tracy = ["dep:tracy-client"]

[dependencies]
anyhow = { workspace = true }
criterion = { version = "0.8", optional = true }
tracy-client = { version = "=0.18.3", optional = true, default-features = false, features = [
    "enable",
    "system-tracing",
    "context-switch-tracing",
    "sampling",
    "only-localhost",
] } # v0.18.3 is compatible with Tracy v0.13.0

[lints]
workspace = true
