[package]
name = "impact_scheduling"
description = "Task scheduling for the Impact engine"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
impact_alloc = { path = "../impact_alloc" }
impact_containers = { path = "../impact_containers" }
log = { path = "../../../interop/log" }
impact_math = { path = "../impact_math" }
impact_thread = { path = "../impact_thread" }
parking_lot = { workspace = true }
tinyvec = { workspace = true }

[lints]
workspace = true
