[package]
name = "impact_alloc"
description = "Allocation for the Impact engine"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
allocator-api2 = "0.2.8"
bumpalo = { version = "3.19", features = ["allocator-api2"] }
impact_log = { path = "../impact_log" }

[lints]
workspace = true
