[package]
name = "impact_intersection_fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.impact_intersection]
path = ".."
features = ["fuzzing"]

[[bin]]
name = "naive_bottom_up_single_aabb_intersection_query"
path = "fuzz_targets/naive_bottom_up_single_aabb_intersection_query.rs"
test = false
doc = false
bench = false

[[bin]]
name = "naive_bottom_up_all_internal_intersections_query"
path = "fuzz_targets/naive_bottom_up_all_internal_intersections_query.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fast_bottom_up_single_aabb_intersection_query"
path = "fuzz_targets/fast_bottom_up_single_aabb_intersection_query.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fast_bottom_up_all_internal_intersections_query"
path = "fuzz_targets/fast_bottom_up_all_internal_intersections_query.rs"
test = false
doc = false
bench = false
