[package]
name = "impact_thread"
description = "Threading for the Impact engine"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
rayon = ["dep:rayon"]

[dependencies]
anyhow = { workspace = true }
crossbeam-channel = "0.5"
impact_log = { path = "../impact_log" }
impact_profiling = { path = "../impact_profiling" }
parking_lot = { workspace = true }
rayon = { workspace = true, optional = true }

[lints]
workspace = true
