[advisories]
ignore = [
    { id = "RUSTSEC-2024-0436", reason = "some dependencies still use old paste crate" },
]

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "CC0-1.0",
    "Zlib",
    "UPL-1.0",
    "OFL-1.1",
    "Ubuntu-font-1.0",
    "zlib-acknowledgement",
]

[sources]
allow-git = [
    "git+https://github.com/lars-frogner/rust-simd-noise",
    "git+https://github.com/roc-lang/roc.git",
]

[bans]
skip-tree = [{ name = "wgpu" }, { name = "winit" }]
